### ISSUE TITLE
ModuleNotFoundError for 'beam_search' 

### ISSUE THREAD

**Issue by shushihsc** [JohnnyPeng18/TypeFix#2]
Hi,

Thank you for release this tool! I am reaching out to report an error when running the `repair.py` script:

```
Traceback (most recent call last):
  File "data/typefix/repair.py", line 7, in <module>
    from beam_search import BeamSearch
ModuleNotFoundError: No module named 'beam_search'
```
It appears that the beam_search module is missing or not accessible. Could it be that the `beam_search.py` file or the relevant module is not included in the repository? 

Your guidance on how to resolve this issue would be greatly appreciated.

**Comment by JohnnyPeng18** [comment]
Thanks for your interest! We use this module from the artifact of AlphaRepair. You can find its artifact at https://zenodo.org/record/6819444. Then you can copy `beam_search.py` of it into the current directory to import it.
